export function buildReaderSettingsSchema({ settings, multiplierLabel, timerText, sessionTimerText, options }) {
    return [
        {
            id: 'tempo',
            title: 'Темп',
            items: [
                {
                    key: 'speed',
                    label: 'Скорость',
                    type: 'range',
                    controlId: 'speed',
                    min: 100,
                    max: 2000,
                    step: 10,
                    meta: `${settings.speed} зн/мин`,
                },
                {
                    key: 'startDelay',
                    label: 'Задержка',
                    type: 'number',
                    controlId: 'startDelay',
                    min: 0,
                    max: 60,
                    step: 1,
                    appendInner: 'с',
                    meta: `${settings.startDelay} с`,
                },
                {
                    key: 'speedMultiplier',
                    label: 'Множитель',
                    type: 'multiplier',
                    controlId: 'speedMultiplier',
                    meta: multiplierLabel,
                },
            ],
        },
        {
            id: 'time',
            title: 'Время',
            items: [
                {
                    key: 'sessionTime',
                    label: 'Время сессии',
                    type: 'readonly',
                    meta: sessionTimerText,
                },
                {
                    key: 'estimateTime',
                    label: 'Оценка времени',
                    type: 'readonly',
                    meta: timerText,
                },
            ],
        },
        {
            id: 'text',
            title: 'Текст',
            items: [
                {
                    key: 'fontSize',
                    label: 'Размер',
                    type: 'range',
                    controlId: 'fontSize',
                    min: 10,
                    max: 100,
                    step: 1,
                    meta: `${settings.fontSize} px`,
                },
                {
                    key: 'lineHeight',
                    label: 'Интерлиньяж',
                    type: 'range',
                    controlId: 'lineHeight',
                    min: 1,
                    max: 2.4,
                    step: 0.1,
                    meta: `${settings.lineHeight}`,
                },
                {
                    key: 'paragraphGap',
                    label: 'Отступ абзаца',
                    type: 'range',
                    controlId: 'paragraphGap',
                    min: 0,
                    max: 2,
                    step: 0.1,
                    meta: `${settings.paragraphGap} em`,
                },
                {
                    key: 'indent',
                    label: 'Красная строка',
                    type: 'range',
                    controlId: 'indent',
                    min: 0,
                    max: 4,
                    step: 0.1,
                    disabled: settings.align === 'center',
                    meta: `${settings.indent} em`,
                },
                {
                    key: 'font',
                    label: 'Шрифт',
                    type: 'select',
                    controlId: 'font',
                    options: options.fonts,
                },
                {
                    key: 'align',
                    label: 'Положение',
                    type: 'select',
                    controlId: 'align',
                    options: options.align,
                },
            ],
        },
        {
            id: 'window',
            title: 'Окно',
            items: [
                {
                    key: 'padding',
                    label: 'Отступы',
                    type: 'range',
                    controlId: 'padding',
                    min: 0,
                    max: 1000,
                    step: 10,
                    meta: `${settings.padding} px`,
                },
                {
                    key: 'overlaySize',
                    label: 'Размер окна',
                    type: 'range',
                    controlId: 'overlaySize',
                    min: 1,
                    max: 10,
                    step: 1,
                    meta: `${settings.overlaySize} стр`,
                },
                {
                    key: 'overlayOpacity',
                    label: 'Прозрачность',
                    type: 'range',
                    controlId: 'overlayOpacity',
                    min: 0,
                    max: 100,
                    step: 5,
                    meta: `${settings.overlayOpacity}%`,
                },
            ],
        },
        {
            id: 'screen',
            title: 'Экран',
            items: [
                {
                    key: 'brightness',
                    label: 'Яркость',
                    type: 'range',
                    controlId: 'brightness',
                    min: 50,
                    max: 150,
                    step: 5,
                    meta: `${settings.brightness}%`,
                },
                {
                    key: 'contrast',
                    label: 'Контраст',
                    type: 'range',
                    controlId: 'contrast',
                    min: 50,
                    max: 150,
                    step: 5,
                    meta: `${settings.contrast}%`,
                },
                {
                    key: 'sepia',
                    label: 'Сепия',
                    type: 'range',
                    controlId: 'sepia',
                    min: 0,
                    max: 100,
                    step: 5,
                    meta: `${settings.sepia}%`,
                },
            ],
        },
        {
            id: 'minimap',
            title: 'Миникарта',
            items: [
                {
                    key: 'showMinimap',
                    label: 'Показывать',
                    type: 'toggle',
                    controlId: 'showMinimap',
                    icon: 'chrome_reader_mode',
                    ariaLabel: 'Показывать миникарту',
                    active: settings.showMinimap !== false,
                    toggleDefaultTrue: true,
                },
                {
                    key: 'minimapWidth',
                    label: 'Ширина',
                    type: 'range',
                    controlId: 'minimapWidth',
                    min: 40,
                    max: 200,
                    step: 5,
                    meta: `${settings.minimapWidth} px`,
                },
                {
                    key: 'minimapScale',
                    label: 'Масштаб',
                    type: 'select',
                    controlId: 'minimapScale',
                    options: options.minimapScale,
                },
            ],
        },
    ];
}
